[package]
name = "linux-gpib-sys"
version = "0.1.11"
authors = ["Julien Salort <julien.salort@ens-lyon.fr>"]
edition = "2024"

[build-dependencies]
bindgen = "0.71"

[lib]
crate-type = ["lib", "cdylib"]
